### PR TITLE
added new package for events provider

### PR DESCRIPTION
**Pull request by sreuland**
Adding new package for soroban events subscriptions. this is to support adding events handling into dapp:

[soroban-tools#458: ](https://github.com/stellar/soroban-tools/issues/458)

### CODE REVIEW

**Comment by esteblock** [comment]
Great! Will check this afternoon

**Comment by esteblock** [comment]
Hello. I merged your first commit https://github.com/esteblock/soroban-react/pull/26/commits/c6ea08a5557ee918d27e0e77ebc36c6dffe981ad

Why to do https://github.com/esteblock/soroban-react/pull/26/commits/5599b9a6acbdaa4fc7108be9558641ea4762ccaa ?

**Comment by esteblock** [comment]
Also, why to change the dependancy:

"soroban-client": "^0.5.0"

to

"soroban-client": "https://github.com/stellar/js-soroban-client#main"
?

thanks :)

**Comment by sreuland** [comment]
thank you @esteblock , to respond on questions:

> Why to do https://github.com/esteblock/soroban-react/commit/5599b9a6acbdaa4fc7108be9558641ea4762ccaa ?
I reverted that on later commit https://github.com/esteblock/soroban-react/pull/26/commits/d4a7dca67e8be0a8b20b7f5b159e8253c51b1d02, I don't think I understood the best way to leverage  workspaces yet, still learning about typescript monorepo

>Also, why to change the dependancy:
"soroban-client": "^0.5.0"

there was a bug fix committed to main for enabling rpc calls with no `params` to work - https://github.com/stellar/js-soroban-client/commit/a52897f24a5b70e39a822c296a0dc2ab2959d713

Where do you think that version bump will cause issue, I'll look into, I have soroban-example-dapp locally using this updated version of soroban-react(via local file path dependency), it's rendering, however, am seeing a problem with generating xdr from a signed tx for the mint EXT, it's err'ing on DecoratedSignature, which is related to stellar-base and js-xdr which come from soroban-client. maybe we can chat more on discord 'soroban-dev' channel, lmk, thanks!

**Comment by sreuland** [comment]
@esteblock , 
> This will carry problems with break changes in soroban-client...

I'll create `0.5.1` release for js-soroban-client from current main which has the `params` [fix](https://github.com/stellar/js-soroban-client/commit/a52897f24a5b70e39a822c296a0dc2ab2959d713), and update this pr to have packages use `0.5.1`

**Comment by esteblock** [comment]
Thanks for your answers. What we can do for now is to track an specific commit of soroban-client :)
Will check this tomorrow.

**Comment by sreuland** [comment]
@esteblock , we cut new [js-soroban-client 0.5.1](https://github.com/stellar/js-soroban-client/releases/tag/v0.5.1), I pushed [change here on pr to pin soroban-client](https://github.com/esteblock/soroban-react/pull/26/commits/aa33ceae43f86b304f76ada3323f000e64f7fbdb). If what's left on this pr looks good, can you merge and cut new release versions of these packages? I'll make use of them in the [soroban-example-dapp pr that is using events ](https://github.com/stellar/soroban-example-dapp/pull/105), thanks!

**Comment by esteblock** [comment]
Hello, checked. Merged and published version 4.3.1 :)

**Pull request merged**
