### PR TITLE
setup to start documentation

### PR DESCRIPTION
**Pull request by mauroepce**
Tasks done:

1.  Project forked
2. soroban-documentation branch created
3. Dependencies installed to work on documentation: 

- prettierrc: setup Prettier, auto-format  to improve readability.
- jsdoc: Automatically generate documentation from comments in code.
- jsdoc-to-markdown: Converts documentation from JSDoc to Markdown, for display on GitHub.
- jsdoc-babel: Allows JSDoc to interpret ES6 code and TypeScript using Babel.

4. "doc" script created to looks for TypeScript files (*.ts) in all subfolders of packages, and generates documentation based on the comments in these files. The resulting documentation is saved in docs/DOCS.md
5. I created a configuration file for JSDoc `jsdoc.json`

### CODE REVIEW

**Comment by esteblock** [comment]
Great. Can you please also add the documentation on each function?

**Comment by mauroepce** [comment]
> Great. Can you please also add the documentation on each function?

Yes. sure!

**Comment by esteblock** [comment]
Hola. Tengo el siguiente error
```
yarn doc
yarn run v1.22.19
$ jsdoc -c jsdoc.json && jsdoc2md packages/**/*.ts > docs/DOCS.md
There are no input files to process.
JSDOC_ERROR: There are no input files to process.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mauroepce** [comment]
> Hola. Tengo el siguiente error
> 
> ```
> yarn doc
> yarn run v1.22.19
> $ jsdoc -c jsdoc.json && jsdoc2md packages/**/*.ts > docs/DOCS.md
> There are no input files to process.
> JSDOC_ERROR: There are no input files to process.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Solved using TypeDoc instead JSDoc

**Pull request merged**
