### PR TITLE
Updates for auth-next

### PR DESCRIPTION
**Pull request by paulbellamy**
Note, this also needs an updated release of `soroban-client` dep, which is still pending release.

### CODE REVIEW

**Comment by paulbellamy** [comment]
@esteblock Do we need to do something specific with lerna to update the interdependencies between the subpackages?

**Comment by esteblock** [comment]
Hello @paulbellamy ,
This is done automatically by lerna.
Just 
```
yarn build
yarn lerna-publish
```

**Comment by esteblock** [comment]
Got some errors while building. Will check this now.

```
arn run v1.22.19
$ lerna run build
lerna notice cli v6.4.0

    ✔  @soroban-react/types:build (5s)
    ✔  @soroban-react/utils:build (6s)
    ✔  @soroban-react/freighter:build (5s)
    ✔  @soroban-react/chains:build (5s)
    ✔  @soroban-react/core:build (5s)
    ✔  @soroban-react/connect-button:build (5s)

    ✖  @soroban-react/contracts:build
$ rm -rf dist
$ tsc
       src/setTrustline.tsx(25,46): error TS2345: Argument of type 'GetAccountResponse' is not assignable to parameter of type 'Account'.
         Type 'GetAccountResponse' is missing the following properties from type 'Account': accountId, sequenceNumber, incrementSequenceNumber
       src/useSendTransaction.tsx(109,26): error TS2339: Property 'prepareTransaction' does not exist on type 'Server'.
       src/useSendTransaction.tsx(116,7): error TS18048: 'txn' is possibly 'undefined'.
       src/useSendTransaction.tsx(117,16): error TS18048: 'txn' is possibly 'undefined'.
       src/useSendTransaction.tsx(120,51): error TS18048: 'txn' is possibly 'undefined'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       
    ✔  @soroban-react/wallet-data:build (5s)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target build for 8 projects (26s)
 
    ✔    7/8 succeeded [0 read from cache]
 
    ✖    1/8 targets failed, including the following:
         - @soroban-react/contracts:build
```

**Comment by esteblock** [comment]
Was by bad, I forgot to install the new dependencies.
Seems to be all ok. Merged and published!

**Pull request merged**
